import {
  FcAutomatic,
  FcCalendar,
  FcCollaboration,
  FcDocument,
  FcHome,
  FcManager,
  FcOvertime,
  FcParallelTasks,
  FcServices,
  FcSettings,
  FcSurvey,
} from 'react-icons/fc';

export const dockLinks = [
  { id: 1, name: 'Home', path: '/dashboard', icon: FcHome },
  {
    id: 2,
    name: 'Patients',
    path: '/dashboard/patients',
    icon: FcCollaboration,
  },
  { id: 3, name: 'Calendar', path: '/dashboard/calendar', icon: FcCalendar },
  {
    id: 4,
    name: 'Appointments',
    path: '/dashboard/appointments',
    icon: FcOvertime,
  },
  { id: 5, name: 'Employees', path: '/dashboard/employees', icon: FcManager },
  {
    id: 6,
    name: 'Prescriptions',
    path: '/dashboard/prescriptions',
    icon: FcSurvey,
  },
  { id: 7, name: 'Tasks', path: '/dashboard/tasks', icon: FcParallelTasks },
  { id: 8, name: 'Documents', path: '/dashboard/documents', icon: FcDocument },
  { id: 10, name: 'Services', path: '/dashboard/services', icon: FcServices },
  { id: 9, name: 'Settings', path: '/dashboard/settings', icon: FcSettings },
];

export const chronicDiseases = [
  'Acquired Immunodeficiency Syndrome (AIDS)',
  "Addison's Disease",
  'Alpha-1 Antitrypsin Deficiency',
  "Alzheimer's Disease",
  'Amyotrophic Lateral Sclerosis (ALS)',
  'Ankylosing Spondylitis',
  'Asthma',
  'Attention Deficit Hyperactivity Disorder (ADHD)',
  'Autism Spectrum Disorder',
  'Autonomic Dysfunction',
  "Behcet's Disease",
  'Bipolar Disorder',
  'Bronchiectasis',
  'Chronic Abdominal Pain',
  'Chronic Adjustment Disorders',
  'Chronic Appendicitis',
  'Chronic Autoimmune Diseases',
  'Chronic Bacterial Diseases',
  'Chronic Bacterial Infections',
  'Chronic Behavioral Disorders',
  'Chronic Blood Infections',
  'Chronic Bone Infections',
  'Chronic Brain Infections',
  'Chronic Bronchitis',
  'Chronic Cardiovascular Diseases',
  'Chronic Cognitive Disorders',
  'Chronic Colitis',
  'Chronic Depression',
  'Chronic Dermatitis',
  'Chronic Developmental Disorders',
  'Chronic Duodenal Ulcer',
  'Chronic Eating Disorders',
  'Chronic Elimination Disorders',
  'Chronic Endocrine Disorders',
  'Chronic Endometritis',
  'Chronic Environmental Diseases',
  'Chronic Epilepsy',
  'Chronic Fatigue Syndrome',
  'Chronic Feeding and Eating Disorders',
  'Chronic Fungal Diseases',
  'Chronic Fungal Infections',
  'Chronic Gastric Reflux',
  'Chronic Gastric Ulcer',
  'Chronic Gastritis',
  'Chronic Gastrointestinal Diseases',
  'Chronic Genitourinary Diseases',
  'Chronic Gonad Infections',
  'Chronic Gout',
  "Chronic Graves' Disease",
  "Chronic Hashimoto's Thyroiditis",
  'Chronic Headaches',
  'Chronic Hematological Disorders',
  'Chronic Hemochromatosis',
  'Chronic Hepatic Encephalopathy',
  'Chronic Hepatitis',
  'Chronic Hepatitis A',
  'Chronic Hepatitis B',
  'Chronic Hepatitis C',
  'Chronic Hepatitis D',
  'Chronic Hepatitis E',
  'Chronic Hereditary Angioedema',
  'Chronic HIV',
  'Chronic Hyperthyroidism',
  'Chronic Hypothyroidism',
  'Chronic Idiopathic Pulmonary Fibrosis',
  'Chronic Inflammatory Demyelinating Polyneuropathy',
  'Chronic Inflammatory Diseases',
  'Chronic Inflammatory Skin Conditions',
  'Chronic Intestinal Infections',
  'Chronic Irritable Bowel Syndrome (IBS)',
  'Chronic Joint Infections',
  'Chronic Kidney Disease',
  'Chronic Kidney Infections',
  'Chronic Laryngitis',
  'Chronic Learning Disorders',
  'Chronic Leukemia',
  'Chronic Liver Infections',
  'Chronic Lyme Disease',
  'Chronic Lymphocytic Leukemia',
  'Chronic Lymphocytic Thyroiditis',
  'Chronic Major Depressive Disorder',
  'Chronic Marfan Syndrome',
  "Chronic Meniere's Disease",
  'Chronic Metabolic Disorders',
  'Chronic Mitochondrial Diseases',
  'Chronic Mood Disorders',
  'Chronic Motor Disorders',
  'Chronic Muscle Infections',
  'Chronic Musculoskeletal Diseases',
  'Chronic Myasthenia Gravis',
  'Chronic Mycoplasma Infections',
  'Chronic Myelogenous Leukemia',
  'Chronic Myocarditis',
  'Chronic Nephritis',
  'Chronic Neurocognitive Disorders',
  'Chronic Neurodegenerative Diseases',
  'Chronic Neurological Diseases',
  'Chronic Neuroinflammatory Diseases',
  'Chronic Neutropenia',
  "Chronic Non-Hodgkin's Lymphoma",
  'Chronic Nutritional Deficiencies',
  'Chronic Obesity',
  'Chronic Occupational Diseases',
  'Chronic Oral Health Disorders',
  'Chronic Osteoarthritis',
  'Chronic Osteoporosis',
  'Chronic Otitis Externa',
  'Chronic Otitis Media',
  'Chronic Pancreatic Infections',
  'Chronic Pancreatitis',
  'Chronic Parasitic Diseases',
  'Chronic Parasitic Infections',
  'Chronic Parathyroid Gland Infections',
  "Chronic Parkinson's Disease",
  'Chronic Pelvic Pain',
  'Chronic Peripheral Artery Disease',
  'Chronic Personality Disorders',
  'Chronic Pituitary Gland Infections',
  'Chronic Polycystic Ovary Syndrome (PCOS)',
  'Chronic Post-Traumatic Stress Disorder (PTSD)',
  'Chronic Prostatitis',
  'Chronic Protozoal Diseases',
  'Chronic Psoriasis',
  'Chronic Pulmonary Hypertension',
  'Chronic Respiratory Diseases',
  'Chronic Respiratory Infections',
  'Chronic Rheumatoid Arthritis',
  'Chronic Rhinitis',
  'Chronic Schizophrenia',
  'Chronic Sensory Disorders',
  'Chronic Sexual Health Disorders',
  'Chronic Sinus Headache',
  'Chronic Sinus Infections',
  'Chronic Sinusitis',
  "Chronic Sjogren's Syndrome",
  'Chronic Skin Infections',
  'Chronic Sleep Apnea',
  'Chronic Sleep Disorders',
  'Chronic Spleen Infections',
  'Chronic Stress Disorders',
  'Chronic Substance Use Disorders',
  'Chronic Systemic Lupus Erythematosus',
  'Chronic Systemic Sclerosis',
  'Chronic Tay-Sachs Disease',
  'Chronic Thalassemia',
  'Chronic Thyroid Disease',
  'Chronic Thyroid Infections',
  'Chronic Thymus Gland Infections',
  'Chronic Trigeminal Neuralgia',
  'Chronic Type 1 Diabetes',
  'Chronic Type 2 Diabetes',
  'Chronic Ulcerative Colitis',
  'Chronic Urinary Tract Infections',
  'Chronic Urticaria',
  'Chronic Vasculitis',
  'Chronic Vector-Borne Diseases',
  'Chronic Viral Diseases',
  'Chronic Viral Hepatitis',
  'Chronic Viral Infections',
  'Chronic Vascular Infections',
  'Chronic Waterborne Diseases',
  "Chronic Wegener's Granulomatosis",
  "Chronic Women's Health Disorders",
  'Cystic Fibrosis',
  'Dementia',
  'Eczema',
  'Endometriosis',
  'Epilepsy',
  'Fabry Disease',
  'Fibromyalgia',
  'Generalized Anxiety Disorder (GAD)',
  'Gluten Sensitivity',
  'Gout',
  "Graves' Disease",
  'Gaucher Disease',
  "Huntington's Disease",
  'Hemophilia',
  'Hepatitis B',
  'Hepatitis C',
  'Human Immunodeficiency Virus (HIV)',
  'Hypertension',
  'Idiopathic Pulmonary Fibrosis',
  'Interstitial Cystitis',
  'Irritable Bowel Syndrome (IBS)',
  'Lupus Nephritis',
  'Lyme Disease',
  'Major Depressive Disorder',
  'Marfan Syndrome',
  "Meniere's Disease",
  'Migraine',
  'Multiple Sclerosis',
  'Myasthenia Gravis',
  'Neurofibromatosis',
  "Non-Hodgkin's Lymphoma",
  'Obesity',
  'Osteoarthritis',
  'Osteoporosis',
  "Parkinson's Disease",
  'Parkinsonism',
  'Peripheral Artery Disease',
  'Polycystic Ovary Syndrome (PCOS)',
  'Post-Traumatic Stress Disorder (PTSD)',
  'Psoriasis',
  'Pulmonary Hypertension',
  'Rheumatoid Arthritis',
  'Sarcoidosis',
  'Schizophrenia',
  'Sickle Cell Disease',
  "Sjogren's Syndrome",
  'Sleep Apnea',
  'Stiff Person Syndrome',
  'Stomach Cancer',
  'Stomach Ulcer',
  'Systemic Lupus Erythematosus',
  'Systemic Sclerosis',
  'Thalassemia',
  'Thyroid Disease',
  'Trigeminal Neuralgia',
  'Type 1 Diabetes',
  'Type 2 Diabetes',
  'Ulcerative Colitis',
  'Vasculitis',
  "Wegener's Granulomatosis",
];
